spring.application.name=Futurum_Technology
# Konfiguracja portu (opcjonalna, domyślnie 8080)
server.port=8080

# Konfiguracja bazy H2
spring.datasource.url=jdbc:h2:mem:Futurum_Technology
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Automatyczne tworzenie/aktualizowanie tabel na podstawie naszych klas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Włączenie konsoli H2 w przeglądarce (bardzo przydatne do podglądu danych)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console